.TH "md___users_zachary_fields__development_bitbucket_irobot-roomba-sdk__r_e_a_d_m_e" 3 "Sun Feb 8 2015" "Version 1.0.0-alpha" "iRobot Roomba 500 Series SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md___users_zachary_fields__development_bitbucket_irobot-roomba-sdk__r_e_a_d_m_e \- A C++ wrapper for the iRobot Roomba Open Interface\&. 

.SS "SAMPLES:"
.PP
< coming soon >
.PP
.SS "TODO:"
.PP
< coming soon >
.PP
.SS "ATTRIBUTION:"
.PP
.IP "\(bu" 2
The makefiles used for compiling the Google Unit Test where taken from Google\&.
.PP
.PP
.SS "LICENSE:"
.PP
.IP "\(bu" 2
The MIT License (MIT)\&. Refer to the LICENSE file for more details\&. 
.PP

