.TH "roomba::series500::oi::OIEncoder" 3 "Tue Nov 11 2014" "Version 1.0.0-alpha" "iRobot Roomba 500 Series SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
roomba::series500::oi::OIEncoder \- 
.PP
The Roomba Open Interface (OI) \fBOIEncoder\fP static class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OIEncoder\&.h>\fP
.PP
Inherited by \fBOIEncoder_TC\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBclock_time_t\fP"
.br
.RI "\fITime representation for the scheduling methods\&. \fP"
.in -1c
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBReturnCode\fP : int8_t { \fBSERIAL_TRANSFER_FAILURE\fP = -100, \fBINVALID_PARAMETER\fP = -10, \fBINVALID_MODE_FOR_REQUESTED_OPERATION\fP = -2, \fBOI_NOT_STARTED\fP = -1, \fBSUCCESS\fP = 0 }"
.br
.RI "\fIReturn codes\&. \fP"
.ti -1c
.RI "typedef std::pair< \fBPitch\fP, uint8_t > \fBnote_t\fP"
.br
.RI "\fIA musical note is defined by the frequency related pitch and length or duration\&. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReturnCode\fP \fBoperator()\fP (const std::vector< uint8_t > &raw_instructions_, const \fBOIMode\fP resulting_mode_=static_cast< \fBOIMode\fP >(-1), const \fBBaudCode\fP resulting_baud_=static_cast< \fBBaudCode\fP >(-1))"
.br
.RI "\fIDirect access to the Open Interface\&. \fP"
.ti -1c
.RI "\fBOIEncoder::ReturnCode\fP \fBconnectToSerialBus\fP (const std::function< size_t(const uint8_t *, const size_t)> fnSerialWrite_, const \fBBaudCode\fP baud_code_=BAUD_115200)"
.br
.RI "\fIEstablishes a serial channel with the hardware\&. \fP"
.ti -1c
.RI "void \fBend\fP (void) const "
.br
.RI "\fIReleases control of the Roomba\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBstart\fP (void)"
.br
.RI "\fIStarts the OI\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBbaud\fP (const \fBBaudCode\fP baud_code_)"
.br
.RI "\fISets the baud rate in bits per second (bps)\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBcontrol\fP (void)"
.br
.RI "\fIThe effect and usage of the Control command are identical to the Safe command\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBsafe\fP (void)"
.br
.RI "\fIPuts the OI into Safe mode\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBfull\fP (void)"
.br
.RI "\fIPuts the OI into Full mode\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBclean\fP (void)"
.br
.RI "\fIStarts the default cleaning mode\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBmax\fP (void)"
.br
.RI "\fIStarts the Max cleaning mode\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBspot\fP (void)"
.br
.RI "\fIStarts the Spot cleaning mode\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBseekDock\fP (void)"
.br
.RI "\fISends Roomba to the dock\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBschedule\fP (const bitmask::Days day_mask_, const \fBclock_time_t\fP *const clock_times_) const "
.br
.RI "\fISends Roomba a new schedule\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBsetDayTime\fP (const \fBDay\fP day_, const \fBclock_time_t\fP clock_time_) const "
.br
.RI "\fISets Roomba’s clock\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBpower\fP (void)"
.br
.RI "\fIPowers down Roomba\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBdrive\fP (const int16_t velocity_, const int16_t radius_) const "
.br
.RI "\fIControls Roomba’s drive wheels\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBdriveDirect\fP (const int16_t left_wheel_velocity_, const int16_t right_wheel_velocity_) const "
.br
.RI "\fIControls the forward and backward motion of Roomba’s drive wheels independently\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBdrivePWM\fP (const int16_t left_wheel_pwm_, const int16_t right_wheel_pwm_) const "
.br
.RI "\fIControls the raw forward and backward motion of Roomba’s drive wheels independently\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBmotors\fP (const bitmask::MotorStates motor_state_mask_) const "
.br
.RI "\fIControls the forward and backward motion of Roomba’s main brush, side brush, and vacuum independently\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBpwmMotors\fP (const int8_t main_brush_, const int8_t side_brush_, const int8_t vacuum_) const "
.br
.RI "\fIControls the speed of Roomba’s main brush, side brush, and vacuum independently\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBleds\fP (const bitmask::display::LEDs led_mask_, const uint8_t color_, const uint8_t intensity_) const "
.br
.RI "\fIControls the LEDs\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBschedulingLEDs\fP (const bitmask::Days day_mask_, const bitmask::display::SchedulingLEDs led_mask_) const "
.br
.RI "\fIControls the state of the scheduling LEDs present on the Roomba 560 and 570\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBdigitLEDsRaw\fP (const bitmask::display::DigitN raw_leds_[4]) const "
.br
.RI "\fIControls the 7 segment displays\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBdigitLEDsASCII\fP (const char ascii_leds_[4]) const "
.br
.RI "\fIControls the 7 segment displays using ASCII character codes\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBbuttons\fP (const bitmask::Buttons button_mask_) const "
.br
.RI "\fIPush Roomba’s buttons\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBsong\fP (const uint8_t song_number_, const std::vector< \fBnote_t\fP > &song_) const "
.br
.RI "\fISpecify songs to be played at a later time\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBplay\fP (const uint8_t song_number_) const "
.br
.RI "\fISelect a song to play\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBsensors\fP (const \fBsensors::PacketId\fP packet_id_) const "
.br
.RI "\fIRequest sensor data\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBqueryList\fP (const std::vector< \fBsensors::PacketId\fP > &sensor_list_) const "
.br
.RI "\fIRequest list of sensor packets\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBstream\fP (const std::vector< \fBsensors::PacketId\fP > &sensor_list_) const "
.br
.RI "\fIStart a data stream based on a query list\&. \fP"
.ti -1c
.RI "\fBReturnCode\fP \fBpauseResumeStream\fP (const bool resume_) const "
.br
.RI "\fIStop and restart the stream\&. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBReturnCode\fP \fBpollSensors\fP (const command::OpCode opcode_, const std::vector< \fBsensors::PacketId\fP > &sensor_list_) const "
.br
.RI "\fICore functionality of both \fBqueryList()\fP and \fBstream()\fP \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::function< size_t(const 
.br
uint8_t *, const size_t)> \fB_fnSerialWrite\fP"
.br
.RI "\fIA function supplying access to the serial bus\&. \fP"
.ti -1c
.RI "\fBOIMode\fP \fB_oi_mode\fP"
.br
.RI "\fIThe operating mode of the Open Interface\&. \fP"
.ti -1c
.RI "\fBBaudCode\fP \fB_baud_code\fP"
.br
.RI "\fIThe baud rate associated with the serial bus\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The Roomba Open Interface (OI) \fBOIEncoder\fP static class\&. 

The Roomba Open Interface (OI) \fBOIEncoder\fP is a C++ wrapper for data to be written the serial bus\&. It provides functionality such as request throttling with respect to baud rate, ensuring full parameter sets are delivered to the underlying serial interface, as well as offering error codes without crashing the system\&. 
.SH "Member Typedef Documentation"
.PP 
.SS "typedef std::pair<\fBPitch\fP, uint8_t> \fBroomba::series500::oi::OIEncoder::note_t\fP"

.PP
A musical note is defined by the frequency related pitch and length or duration\&. The information is stored in std::pair data structure where the first member represents the pitch and the second represent a scalar to apply to 1/64th of a second (i\&.e\&. the value 32 is half a second)\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::baud (const \fBBaudCode\fPbaud_code_)"

.PP
Sets the baud rate in bits per second (bps)\&. This command sets the baud rate in bits per second (bps) at which OI commands and data are sent according to the baud code sent in the data byte\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbaud_code_\fP 
.RE
.PP
\fBNote:\fP
.RS 4
The default baud rate at power up is 115200 bps\&. 
.PP
Available in modes: Passive, Safe, or Full\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIINVALID_PARAMETER\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::buttons (const bitmask::Buttonsbutton_mask_) const"

.PP
Push Roomba’s buttons\&. This command lets you push Roomba’s buttons\&. 
.PP
\fBParameters:\fP
.RS 4
\fIbutton_mask_\fP 
.RE
.PP
\fBNote:\fP
.RS 4
The buttons will automatically release after 1/6th of a second\&. 
.PP
Available in modes: Passive, Safe, or Full\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::clean (void)"

.PP
Starts the default cleaning mode\&. 
.PP
\fBNote:\fP
.RS 4
Available in modes: Passive, Safe, or Full\&. 
.PP
Changes mode to: Passive\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::connectToSerialBus (const std::function< size_t(const uint8_t *, const size_t)>fnSerialWrite_, const \fBBaudCode\fPbaud_code_ = \fCBAUD_115200\fP)"

.PP
Establishes a serial channel with the hardware\&. This method must be called before any other methods of this class\&. It establishes a serial channel between the Open Interface class and the underlying hardware\&. The default baud for communicating with the Roomba outside the Open Interface is 115200, if the external microcontroller is unable to communicate at that speed, an alternative baud, 19200, is available\&. To enable the slower baud on the Roomba you must power-on the Roomba by holding down the clean/power button, or the Roomba can be signaled on the baud rate change line\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfnSerialWrite_\fP A function that writes to the serial bus at either 115200 or 19200 baud\&. 
.br
\fI[baud_code_]\fP The baud rate at which the specified serial function will write to the serial bus (default value: BAUD_115200)\&. 
.br
 Non-variable Configuration:
.IP "\(bu" 2
Data bits: 8
.IP "\(bu" 2
Parity: None
.IP "\(bu" 2
Stop bits: 1
.IP "\(bu" 2
Flow Control: None 
.PP
.RE
.PP
\fBWarning:\fP
.RS 4
If the baud rate of fnSerialWrite is not synchronized to the baud rate of the Roomba, then this class will be unable to communicate with the Roomba's Open Interface\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIINVALID_PARAMETER\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::control (void)"

.PP
The effect and usage of the Control command are identical to the Safe command\&. 
.PP
\fBSee also:\fP
.RS 4
\fBOIEncoder::safe\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::digitLEDsASCII (const charascii_leds_[4]) const"

.PP
Controls the 7 segment displays using ASCII character codes\&. This command controls the four 7 segment displays on the Roomba 560 and 570 using ASCII character codes\&. Because a 7 segment display is not sufficient to display alphabetic characters properly, all characters are an approximation 
.PP
\fBParameters:\fP
.RS 4
\fIascii_leds_\fP An ASCII char array (valid values range from (32-126)\&. 
.RE
.PP
\fBNote:\fP
.RS 4
Available in modes: Safe or Full 
.RE
.PP
\fBWarning:\fP
.RS 4
Not all ASCII codes are implemented\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fIINVALID_MODE_FOR_REQUESTED_OPERATION\fP 
.br
\fIINVALID_PARAMETER\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::digitLEDsRaw (const bitmask::display::DigitNraw_leds_[4]) const"

.PP
Controls the 7 segment displays\&. This command controls the four 7 segment displays on the Roomba 560 and 570\&. 
.PP
\fBParameters:\fP
.RS 4
\fIraw_leds_\fP An array representing the four 7 segment display values\&. 
.RE
.PP
\fBNote:\fP
.RS 4
All use red LEDs 
.PP
Available in modes: Safe or Full\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fIINVALID_MODE_FOR_REQUESTED_OPERATION\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::drive (const int16_tvelocity_, const int16_tradius_) const"

.PP
Controls Roomba’s drive wheels\&. This command controls Roomba’s drive wheels\&. A Drive command with a positive velocity and a positive radius makes Roomba drive forward while turning toward the left\&. A negative radius makes Roomba turn toward the right\&. Special cases for the radius make Roomba turn in place or drive straight, as specified below\&. A negative velocity makes Roomba drive backward\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvelocity_\fP (-500 – 500) The average velocity of the drive wheels in millimeters per second (mm/s)\&. 
.br
\fIradius_\fP (-2000 – 2000) The radius in millimeters at which Roomba will turn\&. The radius is measured from the center of the turning circle to the center of Roomba\&. 
.RE
.PP
\fBSpecial cases\fP
.RS 4

.RE
.PP
\fB\fP
.RS 4
Straight = 32768 (0x8000) or 32767 (0x7FFF) 
.RE
.PP
\fB\fP
.RS 4
Turn in place clockwise = -1 
.RE
.PP
\fB\fP
.RS 4
Turn in place counter-clockwise = 1 
.RE
.PP
\fBNote:\fP
.RS 4
Available in modes: Safe or Full\&. 
.RE
.PP
\fBWarning:\fP
.RS 4
Internal and environmental restrictions may prevent Roomba from accurately carrying out some drive commands\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fIINVALID__MODE__FOR_REQUESTED_OPERATION\fP 
.br
\fIINVALID_PARAMETER\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::driveDirect (const int16_tleft_wheel_velocity_, const int16_tright_wheel_velocity_) const"

.PP
Controls the forward and backward motion of Roomba’s drive wheels independently\&. This command lets you control the forward and backward motion of Roomba’s drive wheels independently\&. A positive velocity makes that wheel drive forward, while a negative velocity makes it drive backward\&. 
.PP
\fBParameters:\fP
.RS 4
\fIleft_wheel_velocity_\fP (-500 – 500) The velocity of the left wheel in millimeters per second (mm/s)\&. 
.br
\fIright_wheel_velocity_\fP (-500 – 500) The velocity of the right wheel in millimeters per second (mm/s)\&. 
.RE
.PP
\fBNote:\fP
.RS 4
Available in modes: Safe or Full\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fIINVALID_MODE_FOR_REQUESTED_OPERATION\fP 
.br
\fIINVALID_PARAMETER\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::drivePWM (const int16_tleft_wheel_pwm_, const int16_tright_wheel_pwm_) const"

.PP
Controls the raw forward and backward motion of Roomba’s drive wheels independently\&. This command lets you control the raw forward and backward motion of Roomba’s drive wheels independently\&. A positive PWM makes that wheel drive forward, while a negative PWM makes it drive backward\&. 
.PP
\fBParameters:\fP
.RS 4
\fIleft_wheel_pwm_\fP (-255 – 255) The PWM of the left wheel\&. 
.br
\fIright_wheel_pwm_\fP (-255 – 255) The PWM of the right wheel\&. 
.RE
.PP
\fBNote:\fP
.RS 4
Available in modes: Safe or Full\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fIINVALID_MODE_FOR_REQUESTED_OPERATION\fP 
.br
\fIINVALID_PARAMETER\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "void roomba::series500::oi::OIEncoder::end (void) const"

.PP
Releases control of the Roomba\&. This method will set the OI Mode to passive and return the Roomba to its docking station\&. It will also reinitialize the class member variables to restore it to a clean state\&. 
.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::full (void)"

.PP
Puts the OI into Full mode\&. This command gives you complete control over Roomba by putting the OI into Full mode, and turning off the cliff, wheel-drop and internal charger safety features\&. 
.PP
\fBNote:\fP
.RS 4
Available in modes: Passive, Safe, or Full\&. 
.PP
Changes mode to: Full\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::leds (const bitmask::display::LEDsled_mask_, const uint8_tcolor_, const uint8_tintensity_) const"

.PP
Controls the LEDs\&. This command controls the LEDs common to all models of Roomba 500\&. Clean/Power uses a bicolor (red/green) LED\&. The intensity and color of this LED can be controlled with 8-bit resolution\&. 
.PP
\fBParameters:\fP
.RS 4
\fIled_mask_\fP 
.br
\fIcolor_\fP 0 = green, 255 = red\&. Intermediate values are intermediate colors (orange, yellow, etc)\&. 
.br
\fIintensity_\fP 0 = off, 255 = full intensity\&. Intermediate values are intermediate intensities\&. 
.RE
.PP
\fBNote:\fP
.RS 4
Home and Spot use green LEDs: 0 = off, 1 = on\&. 
.PP
Check Robot uses an orange LED\&. 
.PP
Debris uses a blue LED\&. 
.PP
Available in modes: Safe or Full\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fIINVALID_MODE_FOR_REQUESTED_OPERATION\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::max (void)"

.PP
Starts the Max cleaning mode\&. 
.PP
\fBNote:\fP
.RS 4
Available in modes: Passive, Safe, or Full\&. 
.PP
Changes mode to: Passive\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::motors (const bitmask::MotorStatesmotor_state_mask_) const"

.PP
Controls the forward and backward motion of Roomba’s main brush, side brush, and vacuum independently\&. This command lets you control the forward and backward motion of Roomba’s main brush, side brush, and vacuum independently\&. Motor velocity cannot be controlled with this command, all motors will run at maximum speed when enabled\&. The main brush and side brush can be run in either direction\&. The vacuum only runs forward\&. 
.PP
\fBParameters:\fP
.RS 4
\fImotor_state_mask_\fP 
.RE
.PP
\fBNote:\fP
.RS 4
Available in modes: Safe or Full\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fIINVALID_MODE_FOR_REQUESTED_OPERATION\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::operator() (const std::vector< uint8_t > &raw_instructions_, const \fBOIMode\fPresulting_mode_ = \fCstatic_cast<\fBOIMode\fP>(-1)\fP, const \fBBaudCode\fPresulting_baud_ = \fCstatic_cast<\fBBaudCode\fP>(-1)\fP)"

.PP
Direct access to the Open Interface\&. Direct access sends bytes directly to the Open Interface\&. Direct access is potentially dangerous, because the parameters are not checked and the device can be left in a 'waiting' state\&. 
.PP
\fBParameters:\fP
.RS 4
\fIraw_instructions_\fP A stream of bytes guaranteed to be a valid command chain by the caller\&. 
.br
\fIresulting_baud_\fP The baud rate the Roomba will be using after the execution of the byte stream provided in the data_ parameter\&. 
.br
\fI[resulting_mode_]\fP The OI mode the Roomba will be left in after the execution of the byte stream provided in the data_ parameter\&. 
.RE
.PP
\fBNote:\fP
.RS 4
If resulting_mode_ is not provided, then this function will incur the overhead associated with polling the state of the device to restore the current state\&. 
.RE
.PP
\fBWarning:\fP
.RS 4
If resulting_baud_ is given an erroneous value, the \fBOIEncoder\fP will no longer be able to calculate buffer overrun protection, even if you have synchronized the caller and the Roomba correctly\&. 
.PP
If resulting_mode_ is given an erroneous value, the \fBOIEncoder\fP will be left in an invalid state\&. At this time the stability and behavior of this class become undefined\&. If you are unsure, then you 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::pauseResumeStream (const boolresume_) const"

.PP
Stop and restart the stream\&. This command lets you stop and restart the steam without clearing the list of requested packets\&. 
.PP
\fBParameters:\fP
.RS 4
\fIresume_\fP An argument of false stops the stream without clearing the list of requested packets\&. An argument of true starts the stream using the list of packets last requested\&. 
.RE
.PP
\fBNote:\fP
.RS 4
Available in modes: Passive, Safe, or Full\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBOIEncoder::stream\fP 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::play (const uint8_tsong_number_) const"

.PP
Select a song to play\&. This command lets you select a song to play from the songs added to Roomba using the Song command\&. You must add one or more songs to Roomba using the Song command in order for the Play command to work\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsong_number_\fP (0-4) The number of the song Roomba is to play\&. 
.RE
.PP
\fBNote:\fP
.RS 4
Available in modes: Safe or Full 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBOIEncoder::song\fP 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fIINVALID_MODE_FOR_REQUESTED_OPERATION\fP 
.br
\fIINVALID_PARAMETER\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::pollSensors (const command::OpCodeopcode_, const std::vector< \fBsensors::PacketId\fP > &sensor_list_) const\fC [protected]\fP"

.PP
Core functionality of both \fBqueryList()\fP and \fBstream()\fP Both \fBqueryList()\fP and \fBstream()\fP have identical implementations\&. The only difference is the original Open Interface opcode, which tells the the Roomba to send the data once or until asked not to\&. 
.PP
\fBParameters:\fP
.RS 4
\fIopcode_\fP Send either QUERY_LIST or STREAM 
.br
\fIsensor_list_\fP A vector of packet ids 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBOIEncoder::queryList\fP 
.PP
\fBOIEncoder::stream\fP 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fIINVALID_PARAMETER\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::power (void)"

.PP
Powers down Roomba\&. This command powers down Roomba\&. The OI can be in Passive, Safe, or Full mode to accept this command\&. 
.PP
\fBNote:\fP
.RS 4
Available in modes: Passive, Safe, or Full\&. 
.PP
Changes mode to: Passive\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::pwmMotors (const int8_tmain_brush_, const int8_tside_brush_, const int8_tvacuum_) const"

.PP
Controls the speed of Roomba’s main brush, side brush, and vacuum independently\&. This command lets you control the speed of Roomba’s main brush, side brush, and vacuum independently\&. With each parameter, you specify the duty cycle for the low side driver (max 127)\&. Positive speeds turn the motor in its default (cleaning) direction\&. For example, if you want to control a motor with 25% of battery voltage, choose a duty cycle of 127 * 25% ~ 32\&. 
.PP
\fBParameters:\fP
.RS 4
\fImain_brush_\fP (-127 – 127) 
.br
\fIside_brush_\fP (-127 – 127) 
.br
\fIvacuum_\fP (0 – 127) 
.RE
.PP
\fBNote:\fP
.RS 4
The vacuum only runs forward\&. 
.PP
The main brush and side brush can be run in either direction\&. 
.PP
Default direction for the side brush is counter-clockwise\&. 
.PP
Default direction for the main brush/flapper is inward\&. 
.PP
Available in modes: Safe or Full\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fIINVALID_MODE_FOR_REQUESTED_OPERATION\fP 
.br
\fIINVALID_PARAMETER\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::queryList (const std::vector< \fBsensors::PacketId\fP > &sensor_list_) const"

.PP
Request list of sensor packets\&. This command lets you ask for a list of sensor packets\&. The result is returned once, as in the Sensors command\&. The robot returns the packets in the order you specify\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsensor_list_\fP A vector of packet ids 
.RE
.PP
\fBNote:\fP
.RS 4
Available in modes: Passive, Safe, or Full\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fIINVALID_PARAMETER\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::safe (void)"

.PP
Puts the OI into Safe mode\&. This command puts the OI into Safe mode, enabling user control of Roomba\&. It turns off all LEDs\&. The OI can be in Passive, Safe, or Full mode to accept this command\&. 
.PP
\fBNote:\fP
.RS 4
If a safety condition occurs (see above) Roomba reverts automatically to Passive mode\&. 
.PP
Available in modes: Passive, Safe, or Full\&. 
.PP
Changes mode to: Safe\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::schedule (const bitmask::Daysday_mask_, const \fBclock_time_t\fP *constclock_times_) const"

.PP
Sends Roomba a new schedule\&. This command sends Roomba a new schedule\&. To disable scheduled cleaning, send all 0s\&. 
.PP
\fBParameters:\fP
.RS 4
\fIday_mask_\fP A bitmask representing the days of the week 
.br
\fIclock_times_\fP A sparse array of \fBclock_time_t\fP variables following { Sun time, Mon time, \&.\&.\&., Sat time }\&. 
.RE
.PP
\fBNote:\fP
.RS 4
The day_mask variable will determine which days the array elements will be applied to, disabled days will be zero filled\&. 
.PP
If a \fBclock_time_t\fP variable contains any values out of range, then the corresponding day will be ignored\&. 
.PP
If Roomba’s schedule or clock button is pressed, this command will be ignored\&. 
.PP
Available in modes: Passive, Safe, or Full\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::schedulingLEDs (const bitmask::Daysday_mask_, const bitmask::display::SchedulingLEDsled_mask_) const"

.PP
Controls the state of the scheduling LEDs present on the Roomba 560 and 570\&. 
.PP
\fBParameters:\fP
.RS 4
\fIday_mask_\fP 
.br
\fIled_mask_\fP 
.RE
.PP
\fBNote:\fP
.RS 4
All use red LEDs 
.PP
Available in modes: Safe or Full\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fIINVALID_MODE_FOR_REQUESTED_OPERATION\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::seekDock (void)"

.PP
Sends Roomba to the dock\&. 
.PP
\fBNote:\fP
.RS 4
Available in modes: Passive, Safe, or Full\&. 
.PP
Changes mode to: Passive\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::sensors (const \fBsensors::PacketId\fPpacket_id_) const"

.PP
Request sensor data\&. This command requests the OI to send a packet of sensor data bytes\&. There are 58 different sensor data packets\&. Each provides a value of a specific sensor or group of sensors\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpacket_id_\fP Identifies which of the 58 sensor data packets should be sent back by the OI\&. 
.RE
.PP
\fBNote:\fP
.RS 4
A value of 100 indicates a packet with all of the sensor data\&. Values of 0 through 6 and 101 through 107 indicate specific subgroups of the sensor data\&. 
.PP
Available in modes: Passive, Safe, or Full\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fIINVALID_PARAMETER\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::setDayTime (const \fBDay\fPday_, const \fBclock_time_t\fPclock_time_) const"

.PP
Sets Roomba’s clock\&. 
.PP
\fBParameters:\fP
.RS 4
\fIday_\fP 
.br
\fIclock_time_\fP (hour [0-23] and minute [0-59]) 
.RE
.PP
\fBNote:\fP
.RS 4
If Roomba’s schedule or clock button is pressed, this command will be ignored\&. 
.PP
Available in modes: Passive, Safe, or Full\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fIINVALID_PARAMETER\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::song (const uint8_tsong_number_, const std::vector< \fBnote_t\fP > &song_) const"

.PP
Specify songs to be played at a later time\&. This command lets you specify up to four songs to the OI that you can play at a later time\&. Each song is associated with a song number\&. The Play command uses the song number to identify your song selection\&. Each song can contain up to sixteen notes\&. Each note is associated with a note number that uses MIDI note definitions and a duration that is specified in increments of 1/64th of a second\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsong_number_\fP (0-4) The song number associated with the specific song\&. 
.br
\fIsong_\fP A vector of std::pairs composed of Note and duration\&. 
.RE
.PP
\fBNote:\fP
.RS 4
If you send a second Song command, using the same song number, the old song is overwritten\&. 
.PP
Available in modes: Passive, Safe, or Full\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBOIEncoder::play\fP 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fIINVALID_PARAMETER\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::spot (void)"

.PP
Starts the Spot cleaning mode\&. 
.PP
\fBNote:\fP
.RS 4
Available in modes: Passive, Safe, or Full\&. 
.PP
Changes mode to: Passive\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::start (void)"

.PP
Starts the OI\&. You must always send the Start command before sending any other commands to the OI\&. 
.PP
\fBNote:\fP
.RS 4
Available in modes: Passive, Safe, or Full\&. 
.PP
Changes mode to: Passive\&. Roomba beeps once to acknowledge it is starting from “off” mode\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SS "\fBOIEncoder::ReturnCode\fP roomba::series500::oi::OIEncoder::stream (const std::vector< \fBsensors::PacketId\fP > &sensor_list_) const"

.PP
Start a data stream based on a query list\&. This command starts a stream of data packets\&. The list of packets requested is sent every 15 ms, which is the rate Roomba uses to update data\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsensor_list_\fP A vector of packet ids 
.RE
.PP
\fBNote:\fP
.RS 4
This method of requesting sensor data is best if you are controlling Roomba over a wireless network (which has poor real-time characteristics) with software running on a desktop computer\&. 
.PP
Available in modes: Passive, Safe, or Full\&. 
.RE
.PP
\fBWarning:\fP
.RS 4
It is up to you not to request more data than can be sent at the current baud rate in the 15 ms time slot\&. If more data is requested, the data stream will eventually become corrupted\&. This can be confirmed by checking the checksum\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBOIEncoder::pauseResumeStream\fP 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fISUCCESS\fP 
.br
\fIOI_NOT_STARTED\fP 
.br
\fIINVALID_PARAMETER\fP 
.br
\fISERIAL_TRANSFER_FAILURE\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBBaudCode\fP roomba::series500::oi::OIEncoder::_baud_code\fC [protected]\fP"

.PP
The baud rate associated with the serial bus\&. This variable is used to calculate buffer overrun protection\&. 
.SS "std::function<size_t(const uint8_t *, const size_t)> roomba::series500::oi::OIEncoder::_fnSerialWrite\fC [protected]\fP"

.PP
A function supplying access to the serial bus\&. This function is provided from the call to \fBconnectToSerialBus()\fP after class has been instantiated\&. 
.PP
\fBSee also:\fP
.RS 4
\fBOIEncoder::connectToSerialBus\fP 
.RE
.PP

.SS "\fBOIMode\fP roomba::series500::oi::OIEncoder::_oi_mode\fC [protected]\fP"

.PP
The operating mode of the Open Interface\&. This variable is used to track the current operating mode of the open interface (i\&.e\&. Off, Passive, Safe, Full) 

.SH "Author"
.PP 
Generated automatically by Doxygen for iRobot Roomba 500 Series SDK from the source code\&.
