.TH "/Users/zachary_fields/Development/bitbucket/irobot-roomba-500-series-sdk/OIEncoder Directory Reference" 3 "Tue Nov 11 2014" "Version 1.0.0-alpha" "iRobot Roomba 500 Series SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/zachary_fields/Development/bitbucket/irobot-roomba-500-series-sdk/OIEncoder Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBgtest\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBOIEncoder\&.cpp\fP"
.br
.ti -1c
.RI "file \fBOIEncoder\&.h\fP"
.br
.in -1c
