.TH "DefaultPIDController_TC" 3 "Sat Aug 9 2014" "Version 1.0.0-alpha" "iRobot Roomba 500 Series SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DefaultPIDController_TC \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits PIDController\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDefaultPIDController_TC\fP (thermocouple::uV2C_func_t microvoltsToCelcius_, const float set_point_)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for iRobot Roomba 500 Series SDK from the source code\&.
