.TH "OpenInterface_TC" 3 "Fri Sep 19 2014" "Version 1.0.0-alpha" "iRobot Roomba 500 Series SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenInterface_TC \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBroomba::series500::OpenInterface\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for iRobot Roomba 500 Series SDK from the source code\&.
