.TH "roomba::series500::OpenInterface::clock_time_t" 3 "Thu Aug 21 2014" "Version 1.0.0-alpha" "iRobot Roomba 500 Series SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
roomba::series500::OpenInterface::clock_time_t \- 
.PP
Time representation for the scheduling methods\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OI\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBclock_time_t\fP (uint8_t hour_=0, uint8_t minute_=0)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBhour\fP"
.br
.RI "\fIhour (0-23) \fP"
.ti -1c
.RI "uint8_t \fBminute\fP"
.br
.RI "\fIminute (0-59) \fP"
.in -1c
.SH "Detailed Description"
.PP 
Time representation for the scheduling methods\&. 

This struct represents time in military time with the two fields hour and minute\&. The values in the structure are initialized to zero upon instantiation\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for iRobot Roomba 500 Series SDK from the source code\&.
