.TH "roomba::series500" 3 "Fri Sep 19 2014" "Version 1.0.0-alpha" "iRobot Roomba 500 Series SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
roomba::series500 \- 
.PP
The Roomba 500 Series Model (5xx)  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBoi\fP"
.br
.RI "\fIThe Roomba Open Interface (OI) \fP"
.in -1c
.SH "Detailed Description"
.PP 
The Roomba 500 Series Model (5xx) 

The third-generation, 500-series, Roomba was first introduced in August 2007, and features a forward-looking infrared sensor to detect obstacles and reduce speed, a 'Dock' button, improved mechanical components, smoothness of operation & a modular design making part replacement trivial\&. It also introduced customizable decorative face plates\&. The Roomba 530 came with two Virtual Walls and a recharging dock\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for iRobot Roomba 500 Series SDK from the source code\&.
