.TH "roomba" 3 "Tue Nov 11 2014" "Version 1.0.0-alpha" "iRobot Roomba 500 Series SDK" \" -*- nroff -*-
.ad l
.nh
.SH NAME
roomba \- 
.PP
The iRobot Roomba autonomous robotic vacuum cleaner\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBseries500\fP"
.br
.RI "\fIThe Roomba 500 Series Model (5xx) \fP"
.in -1c
.SH "Detailed Description"
.PP 
The iRobot Roomba autonomous robotic vacuum cleaner\&. 

Roomba was introduced in 2002\&. As of Feb 2014, over 10 million units have been sold worldwide\&. Roomba features a set of basic sensors that help it perform tasks\&. For instance, the Roomba is able to change direction on encountering obstacles, detect dirty spots on the floor, and detect steep drops to keep it from falling down stairs\&. It uses two independently operating wheels that allow 360 degree turns\&. Additionally, it can adapt to perform other more 'creative' tasks using an embedded computer in conjunction with the Roomba Open Interface\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for iRobot Roomba 500 Series SDK from the source code\&.
